[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
dex_solana = "13kxuZC81hWTX1UnDDxQdpTbTgqug5nHJYiMo2bHC3h7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/pumpfun.amm.buy.test.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = true

[test.validator]
bind_address = "127.0.0.1"
faucet_port = 9901
url = "https://kora-8cwrc2-fast-mainnet.helius-rpc.com"
ledger = "./test-ledger"
rpc_port = 8899

[[test.validator.account]]
address = "DZBDHnfn3McJpf8QXQ1PVsnE7VTZ2vVLbMZgYq9Qpump"
filename = "tests/mint.json"

[[test.validator.clone]]
address = "So11111111111111111111111111111111111111112" # WOL
[[test.validator.clone]]
address = "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB" # USDT
[[test.validator.clone]]
address = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v" # USDC

[[test.validator.clone]]
address = "pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA" # pumpfun amm
[[test.validator.clone]]
address = "2waPHeXir1Ukt3TpFuUsjZdp59k6zFaPGZqkW7HRndfh" # pool
[[test.validator.clone]]
address = "ADyA8hdefvWN2dbGGWFotbzWxrAvLW83WG6QCVXvJKqw" # global_config
[[test.validator.clone]]
address = "8wdL6Htn346sjpmosDm3gCJXkDbWBbeCc3LmYRNApump" # base_mint
[[test.validator.clone]]
address = "7MBZvqy3HHv8NmNidbo7Xv9JE4UCrYP1mhk4sF794oVR" # pool_base_token_account
[[test.validator.clone]]
address = "6nW547d5bGxymRVhTe5rQxRE86nLECiGmBRAe9xMySHz" # pool_quote_token_account
[[test.validator.clone]]
address = "62qc2CNXwrYqQScmEdiZFFAnJR262PxWEuNQtxfafNgV" # protocol_fee_recipient
[[test.validator.clone]]
address = "94qWNrtmfn42h3ZjUZwWvK1MEo9uVmmrBPd2hpNjYDjb" # protocol_fee_recipient_token_account
[[test.validator.clone]]
address = "GS4CU59F31iL7aR2Q8zVS8DRrcRnXX1yjQ66TqNVQnaR" # event_authority
[[test.validator.clone]]
address = "AkY6SmpmnZTJUxeBDpj5hH83YBYfgMTcbf4wLo9JzuuM" # coin_creator_vault_ata
[[test.validator.clone]]
address = "C2aFPdENg4A2HQsmrd5rTw5TaYBX5Ku887cWjbFKtZpw" # global_volume_accumulator
[[test.validator.clone]]
address = "5PHirr8joyTMp9JMm6nW7hNDVyEYdkzDqazxPD7RaTjx" # fee_config
[[test.validator.clone]]
address = "pfeeUxB6jkeY1Hxd7CsFCAjcbHA9rWtchMGdZ6VojVZ" # fee_program
